# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

#Pipelines - Contains multiple stages like build, test, deploy - stages ->jobs->Tasks(steps)
jobs:
- job: Job1
  steps:
  - script: echo job1 Hello, world --Job1- Changed file !
    displayName: 'Run a one-line script'
  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
- job: Job2
  dependsOn: Job1
  steps:
  - script: echo Jobb2 depends on Job1!
    displayName: 'Run a one-line script'
- job: Job3
  dependsOn: Job1
  steps:
  - script: echo Jobb3 depends on Job2 execution!
    displayName: 'Run a one-line script'
- job: Job4
  dependsOn: 
  - Job2
  - Job3
  steps:
  - script: echo Job4!
    displayName: 'Run a one-line script'