# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs: 
  - job: FirstJob
    steps:
      - bash: echo Build First Job
  - job: SecondJob
    steps:
      - bash: echo Build Second Job     
- stage: DevDeploy
  jobs: 
  - job: Dev Deploy Job
    steps:
      - bash: echo Dev Deploy Job
- stage: QADeploy
  jobs: 
  - job: QA Deploy Job
    steps:
      - bash: echo QA Deploy Job
- stage: ProdDeploy
  jobs: 
  - job: Prod Deploy Job
    steps:
      - bash: echo Prod Deploy Job

